steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/slip-checker', '.']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'slip-checker',
      '--image', 'gcr.io/$PROJECT_ID/slip-checker',
      '--region', 'asia-southeast1',
      '--memory', '1024Mi',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--set-env-vars',
      'PORT=8080,LINE_CHANNEL_ACCESS_TOKEN=hHNGJCxlhyY1OJCvzOhP/QF/iRYqNDPEZ+z8symFqo5ZUrJ8c5uCTVhFdjQB49iUHhMJy8hHx2wsA7BGjFKXsUH1RpGZuoMvQ1JeVJwu9WUSOI7f2DxxZjtAONI8cgDoIMZmTnQE14HkCIIfUQX/HwdB04t89/1O/w1cDnyilFU=,LINE_CHANNEL_SECRET=f50a96557adbbb35308dd5c3d58ee708,SHEET_ID_MAIN=1iPcCNAyZg13xhj5pg_JgyFitcMqU2mBs,SHEET_ID_LOG=1vkknyuGSklpED8gpWH_CTMCZ7FvqVcW_cc2h9F6fGRk'
    ]

images:
  - 'gcr.io/$PROJECT_ID/slip-checker'
